service: sls-url-shortener

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1
  apiGateway:
    apiKeySourceType: HEADER
  versionFunctions: false
  timeout: 30
  environment: 
    REGION: ap-southeast-1
    STAGE: local
    BASE_URL: http://localhost:3000

plugins:
  - serverless-dynamodb
  - serverless-offline

custom: 
  serverless-dynamodb:
    stages:
      - local
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
  env: local

functions:
  list:
    handler: handler.list
    events:
      - http:
          path: list-urls
          method: get
  generate:
    handler: handler.generate
    events:
      - http:
          path: generate-url
          method: post          
  redirect:
    handler: handler.redirect
    events:
      - http:
        path: s/${id}
        method: get

resources:
  Resources:
    UrlTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: urls
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1